name: Read Group Repos

on:
  push:
    branches:
      - main  

jobs:
  read-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: List Repositories
        id: list-repos
        run: |
          AUTH_TOKEN="${{ secrets.AUTH_TOKEN }}"
          ORGANIZATION="cyman-paper-translation"
          
          # 获取组织中的仓库列表
          REPOS=$(curl -s -H "Authorization: token $AUTH_TOKEN" \
                   "https://api.github.com/orgs/$ORGANIZATION/repos?per_page=100" | \
                   jq -r '.[].full_name')
          
          for REPO in $REPOS; do
            echo "Repository: $REPO"
            # 读取仓库内容
            CONTENT=$(curl -s -H "Authorization: token $AUTH_TOKEN" \
                       "https://api.github.com/repos/$REPO/contents")
            echo "$CONTENT"
          done